version: '3.8'

services:
  pseudobridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pseudobridge_container
    volumes:
      - .:/PseudoBridge
      - ~/Desktop:/root/desktop
      - ~/Applications:/root/applications
    command: ["python3.11", "start.py"]
